/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // APPFORGE design tokens
        'tertiary-container': '#f7e953',
        'inverse-primary': '#bfff5a',
        'secondary-fixed-dim': '#d2dd52',
        'primary-dim': '#3a5800',
        surface: '#f7f7f2',
        'on-tertiary-container': '#5b5500',
        'tertiary-fixed': '#f7e953',
        'on-surface': '#2d2f2c',
        'surface-container-low': '#f1f1ec',
        'secondary-fixed': '#e0eb5f',
        'on-secondary-container': '#505600',
        'tertiary-fixed-dim': '#e8da46',
        'surface-variant': '#dcddd7',
        tertiary: '#645d00',
        error: '#b02500',
        'on-primary': '#dbffa3',
        'inverse-on-surface': '#9c9d99',
        primary: '#436500',
        'on-tertiary-fixed': '#484200',
        'on-primary-container': '#3f6000',
        'secondary-dim': '#4e5400',
        'surface-container-highest': '#dcddd7',
        'surface-tint': '#436500',
        outline: '#767773',
        'tertiary-dim': '#575100',
        'surface-container-high': '#e2e3dd',
        'surface-bright': '#f7f7f2',
        'on-error-container': '#520c00',
        'surface-dim': '#d3d5cf',
        'secondary-container': '#e0eb5f',
        'on-secondary-fixed-variant': '#596000',
        'surface-container': '#e8e9e3',
        'on-primary-fixed-variant': '#476b00',
        'primary-container': '#bfff5a',
        'primary-fixed': '#bfff5a',
        'on-error': '#ffefec',
        'on-secondary-fixed': '#3e4300',
        'on-primary-fixed': '#314c00',
        'error-dim': '#b92902',
        'on-secondary': '#f0fc6d',
        'outline-variant': '#adada9',
        'error-container': '#f95630',
        'inverse-surface': '#0d0f0c',
        'on-tertiary': '#fff5a0',
        secondary: '#596000',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#665f00',
        'primary-fixed-dim': '#b1f04c',
        'on-surface-variant': '#5a5c58',
        background: '#f7f7f2',
        'on-background': '#2d2f2c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Epilogue', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['JetBrains Mono', 'monospace'],
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translate3d(0, 14px, 0)' },
          '100%': { opacity: '1', transform: 'translate3d(0, 0, 0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translate3d(0, 0, 0)' },
          '50%': { transform: 'translate3d(0, -10px, 0)' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-120%)' },
          '100%': { transform: 'translateX(120%)' },
        },
      },
      animation: {
        'fade-up': 'fade-up 700ms cubic-bezier(0.2, 0.8, 0.2, 1) both',
        'fade-in': 'fade-in 500ms ease-out both',
        float: 'float 5.5s ease-in-out infinite',
        shimmer: 'shimmer 2.2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
